name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --all-extras --dev
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v || echo "No tests found, skipping..."
    
    - name: Test conversion
      run: |
        echo "Testing basic conversion..."
        uv run mihomo2singbox input.yaml -o test_output.json
        echo "Testing TUN mode..."
        uv run mihomo2singbox input.yaml --tun-simple -o test_tun_output.json
    
    - name: Check code formatting
      run: |
        uv run ruff check . || echo "Ruff not configured, skipping..."
    
    - name: Type checking
      run: |
        uv run mypy mihomo2singbox/ || echo "MyPy not configured, skipping..."

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync
    
    - name: Build package
      run: uv build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
    
    - name: Publish to PyPI
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv tool install twine
        uv tool run twine upload dist/*
